name: Deploy to Sepolia

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      verify:
        description: 'Verify contracts on Etherscan'
        required: false
        default: true
        type: boolean

env:
  FOUNDRY_PROFILE: default

jobs:
  deploy:
    name: Deploy VendingMachine to Sepolia
    runs-on: ubuntu-latest
    environment: sepolia
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build contracts
        run: forge build

      - name: Set environment
        id: network-env
        run: |
          echo "RPC_URL=${{ secrets.SEPOLIA_RPC_URL }}" >> $GITHUB_ENV
          echo "ETHERSCAN_API=${{ secrets.ETHERSCAN_API_KEY }}" >> $GITHUB_ENV
          echo "CHAIN_ID=11155111" >> $GITHUB_ENV
          echo "EXPLORER_URL=https://sepolia.etherscan.io" >> $GITHUB_OUTPUT
          echo "PRIVATE_KEY=${{ secrets.DEPLOYER_PRIVATE_KEY }}" >> $GITHUB_ENV

      - name: Deploy VendingMachine
        id: deploy
        run: |
          OUTPUT=$(forge script script/DeployVendingMachine.s.sol:DeployVendingMachine \
            --rpc-url $RPC_URL \
            --broadcast \
            --slow \
            -vvv)
          
          echo "$OUTPUT"
          
          # Extract deployed addresses from output
          VENDING_ADDRESS=$(echo "$OUTPUT" | grep -o "VendingMachine deployed at: 0x[a-fA-F0-9]*" | awk '{print $4}')
          TOKEN_ADDRESS=$(echo "$OUTPUT" | grep -o "VoteToken deployed at: 0x[a-fA-F0-9]*" | awk '{print $4}')
          
          echo "VENDING_ADDRESS=$VENDING_ADDRESS" >> $GITHUB_OUTPUT
          echo "TOKEN_ADDRESS=$TOKEN_ADDRESS" >> $GITHUB_OUTPUT

      - name: Wait for blockchain indexing
        if: ${{ github.event.inputs.verify == 'true' || github.event.inputs.verify == null }}
        run: |
          echo "Waiting 30 seconds for blockchain indexing..."
          sleep 30

      - name: Verify contracts
        if: ${{ github.event.inputs.verify == 'true' || github.event.inputs.verify == null }}
        run: |
          echo "Verifying VendingMachine at ${{ steps.deploy.outputs.VENDING_ADDRESS }}"
          
          # Extract constructor arguments from broadcast file
          BROADCAST_FILE="broadcast/DeployVendingMachine.s.sol/$CHAIN_ID/run-latest.json"
          echo "Reading constructor arguments from: $BROADCAST_FILE"
          
          # Get the transaction that deployed VendingMachine
          DEPLOY_TX=$(cat $BROADCAST_FILE | jq -r '.transactions[] | select(.contractName == "VendingMachine")')
          
          # Extract constructor arguments (removing the 0x prefix and bytecode)
          # The arguments field contains the raw constructor arguments
          CONSTRUCTOR_ARGS=$(echo "$DEPLOY_TX" | jq -r '.arguments' | sed 's/\[//g' | sed 's/\]//g' | sed 's/"//g' | sed 's/,//g' | sed 's/ //g')
          
          echo "Constructor arguments: $CONSTRUCTOR_ARGS"
          
          # Build the constructor arguments string for forge verify-contract
          # The VendingMachine constructor takes multiple parameters, we need to encode them properly
          forge verify-contract \
            ${{ steps.deploy.outputs.VENDING_ADDRESS }} \
            src/contracts/VendingMachine.sol:VendingMachine \
            --chain-id $CHAIN_ID \
            --etherscan-api-key $ETHERSCAN_API \
            --compiler-version v0.8.20+commit.a1b79de6 \
            --watch || {
              echo "::error::Contract verification failed"
              exit 1
            }

      - name: Create deployment summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Network: Sepolia" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Contract | Address | Explorer |" >> $GITHUB_STEP_SUMMARY
          echo "|----------|---------|----------|" >> $GITHUB_STEP_SUMMARY
          echo "| VendingMachine | \`${{ steps.deploy.outputs.VENDING_ADDRESS }}\` | [View](${{ steps.network-env.outputs.EXPLORER_URL }}/address/${{ steps.deploy.outputs.VENDING_ADDRESS }}) |" >> $GITHUB_STEP_SUMMARY
          echo "| VoteToken | \`${{ steps.deploy.outputs.TOKEN_ADDRESS }}\` | [View](${{ steps.network-env.outputs.EXPLORER_URL }}/address/${{ steps.deploy.outputs.TOKEN_ADDRESS }}) |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Deployment Details" >> $GITHUB_STEP_SUMMARY
          echo "- Deployer: \`${{ secrets.DEPLOYER_ADDRESS }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Timestamp: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY

      - name: Save deployment artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-sepolia-${{ github.run_number }}
          path: |
            broadcast/
            out/

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const vendingAddress = '${{ steps.deploy.outputs.VENDING_ADDRESS }}';
            const tokenAddress = '${{ steps.deploy.outputs.TOKEN_ADDRESS }}';
            const explorerUrl = '${{ steps.network-env.outputs.EXPLORER_URL }}';
            
            const comment = `## 🚀 Deployed to Sepolia
            
            **VendingMachine**: [${vendingAddress}](${explorerUrl}/address/${vendingAddress})
            **VoteToken**: [${tokenAddress}](${explorerUrl}/address/${tokenAddress})
            
            Deployed from commit: ${context.sha}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });